@startuml

/' diagram meta data start
config=StructureConfiguration;
{
  "projectClassification": {
    "searchMode": "OpenProject", // OpenProject, AllProjects
    "includedProjects": "",
    "pathEndKeywords": "*.impl",
    "isClientPath": "",
    "isClientName": "",
    "isTestPath": "",
    "isTestName": "",
    "isMappingPath": "",
    "isMappingName": "",
    "isDataAccessPath": "",
    "isDataAccessName": "",
    "isDataStructurePath": "",
    "isDataStructureName": "",
    "isInterfaceStructuresPath": "",
    "isInterfaceStructuresName": "",
    "isEntryPointPath": "",
    "isEntryPointName": "",
    "treatFinalFieldsAsMandatory": false
  },
  "graphRestriction": {
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "removeByInheritance": "", // inheritance/annotation based filtering is done in a second step
    "removeByAnnotation": "",
    "removeByClassPackage": "", // cleanup the graph after inheritance/annotation based filtering is done
    "removeByClassName": "",
    "cutMappings": false,
    "cutEnum": true,
    "cutTests": true,
    "cutClient": true,
    "cutDataAccess": true,
    "cutInterfaceStructures": true,
    "cutDataStructures": true,
    "cutGetterAndSetter": true,
    "cutConstructors": false
  },
  "graphTraversal": {
    "forwardDepth": 2,
    "backwardDepth": 2,
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "OutputBuilder;ListOutputBuilder;ArchiveOutputBuilder;",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "hideMappings": false,
    "hideDataStructures": false,
    "hidePrivateMethods": false,
    "hideInterfaceCalls": false, // indirection: implementation -> interface (is hidden) -> implementation
    "onlyShowApplicationEntryPoints": false, // root node is included
    "useMethodCallsForStructureDiagram": "BothDirections" // ForwardOnly, BothDirections, No
  },
  "details": {
    "aggregation": "GroupByClass", // ByClass, GroupByClass, None
    "showClassGenericTypes": true,
    "showMethods": true,
    "showMethodParameterNames": true,
    "showMethodParameterTypes": true,
    "showMethodReturnType": true,
    "showPackageLevels": 2,
    "showDetailedClassStructure": true
  },
  "rootClass": "Plugin.IO.Builder.ListOutputBuilder",
  "extensionCallbackMethod": "" // qualified.class.name#methodName - signature: public static String method(String)
}
diagram meta data end '/



digraph g {
    rankdir="TB"
    splines=polyline
    

'nodes 
subgraph cluster_2342 { 
   	label=IO
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   subgraph cluster_2055071053 { 
   	label=Builder
	labeljust=l
	fillcolor="#d8d8d8"
	style=filled
   
   ArchiveOutputBuilder1194353618[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)ArchiveOutputBuilder</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >#   result: StringBuilder [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ ArchiveOutputBuilder()</TD></TR>
<TR><TD ALIGN="LEFT" >+ append(entry: Entry)</TD></TR>
<TR><TD ALIGN="LEFT" >+ append(entryList: List&lt;Entry&gt;)</TD></TR>
<TR><TD ALIGN="LEFT" >+ finalise(): String</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

ListOutputBuilder1194353618[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)ListOutputBuilder</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >#   result: StringBuilder [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ ListOutputBuilder()</TD></TR>
<TR><TD ALIGN="LEFT" >+ append(entry: Entry)</TD></TR>
<TR><TD ALIGN="LEFT" >+ append(entryList: List&lt;Entry&gt;)</TD></TR>
<TR><TD ALIGN="LEFT" >+ finalise(): String</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

OutputBuilder1194353618[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(I)OutputBuilder</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ append(entry: Entry)</TD></TR>
<TR><TD ALIGN="LEFT" >+ append(entryList: List&lt;Entry&gt;)</TD></TR>
<TR><TD ALIGN="LEFT" >+ finalise(): String</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#F1E5FD"
];
} 
} 

'edges    
OutputBuilder1194353618 -> ArchiveOutputBuilder1194353618[arrowhead=none, arrowtail=empty, dir=both];
OutputBuilder1194353618 -> ListOutputBuilder1194353618[arrowhead=none, arrowtail=empty, dir=both];
    
}
@enduml