@startuml

/' diagram meta data start
config=CallConfiguration;
{
  "rootMethod": "Plugin.Application.ConsoleCommands.MainMenu.ShowReadingList#execute()",
  "projectClassification": {
    "searchMode": "OpenProject", // OpenProject, AllProjects
    "includedProjects": "",
    "pathEndKeywords": "*.impl",
    "isClientPath": "",
    "isClientName": "",
    "isTestPath": "",
    "isTestName": "",
    "isMappingPath": "",
    "isMappingName": "",
    "isDataAccessPath": "",
    "isDataAccessName": "",
    "isDataStructurePath": "",
    "isDataStructureName": "",
    "isInterfaceStructuresPath": "",
    "isInterfaceStructuresName": "",
    "isEntryPointPath": "",
    "isEntryPointName": "",
    "treatFinalFieldsAsMandatory": false
  },
  "graphRestriction": {
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "removeByInheritance": "", // inheritance/annotation based filtering is done in a second step
    "removeByAnnotation": "",
    "removeByClassPackage": "", // cleanup the graph after inheritance/annotation based filtering is done
    "removeByClassName": "",
    "cutMappings": false,
    "cutEnum": true,
    "cutTests": true,
    "cutClient": true,
    "cutDataAccess": false,
    "cutInterfaceStructures": false,
    "cutDataStructures": false,
    "cutGetterAndSetter": true,
    "cutConstructors": true
  },
  "graphTraversal": {
    "forwardDepth": 1,
    "backwardDepth": 1,
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "hideMappings": true,
    "hideDataStructures": true,
    "hidePrivateMethods": false,
    "hideInterfaceCalls": false, // indirection: implementation -> interface (is hidden) -> implementation
    "onlyShowApplicationEntryPoints": false, // root node is included
    "useMethodCallsForStructureDiagram": "ForwardOnly" // ForwardOnly, BothDirections, No
  },
  "details": {
    "aggregation": "GroupByClass", // ByClass, GroupByClass, None
    "showMethodParametersTypes": true,
    "showMethodParametersNames": true,
    "showMethodReturnType": true,
    "showPackageLevels": 11,
    "showCallOrder": false,
    "edgeMode": "TypesAndMethods", // TypesOnly, MethodsOnly, TypesAndMethods, MethodsAndDirectTypeUsage
    "showDetailedClassStructure": false
  },
  "rootClass": "Plugin.Application.ConsoleCommands.MainMenu.ShowReadingList",
  "extensionCallbackMethod": "" // qualified.class.name#methodName - signature: public static String method(String)
}
diagram meta data end '/



digraph g {
    rankdir="LR"
    splines=polyline
    

'nodes 
subgraph cluster_1072845520 { 
   	label=Application
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   subgraph cluster_622202847 { 
   	label=ConsoleCommands
	labeljust=l
	fillcolor="#d8d8d8"
	style=filled
   
   subgraph cluster_1516111365 { 
   	label=MainMenu
	labeljust=l
	fillcolor="#c4c4c4"
	style=filled
   
   subgraph cluster_35140543 { 
   	label=ShowReadingList
	labeljust=l
	fillcolor=white
	style=filled
   
   ShowReadingList986665920XXXexecute0[
	label="+ execute(): State"
	style=filled
	fillcolor=white
	tooltip="ShowReadingList

null"
	penwidth=4
	fontcolor=darkgreen
];
} 
} 

subgraph cluster_2076404484 { 
   	label=ConsoleCommand
	labeljust=l
	fillcolor=white
	style=filled
   
   ConsoleCommand4600838XXXexecute0[
	label="+ execute(): State"
	style=filled
	fillcolor=white
	tooltip="ConsoleCommand

null"
	fontcolor=darkgreen
];
} 
} 
} 

subgraph cluster_2342 { 
   	label=IO
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   subgraph cluster_56888846 { 
   	label=Output
	labeljust=l
	fillcolor=white
	style=filled
   
   Output190330273XXXshowHeaderReadingList0[
	label="+ showHeaderReadingList()"
	style=filled
	fillcolor=white
	tooltip="Output

null"
	fontcolor=darkgreen
];

Output190330273XXXshowOutput1808118735[
	label="+ showOutput(message: String)"
	style=filled
	fillcolor=white
	tooltip="Output

null"
	fontcolor=darkgreen
];
} 
} 

'edges    
ConsoleCommand4600838XXXexecute0 -> ShowReadingList986665920XXXexecute0;
ShowReadingList986665920XXXexecute0 -> Output190330273XXXshowHeaderReadingList0;
ShowReadingList986665920XXXexecute0 -> Output190330273XXXshowOutput1808118735;
    
}
@enduml