@startuml

/' diagram meta data start
config=StructureConfiguration;
{
  "projectClassification": {
    "searchMode": "OpenProject", // OpenProject, AllProjects
    "includedProjects": "",
    "pathEndKeywords": "*.impl",
    "isClientPath": "",
    "isClientName": "",
    "isTestPath": "",
    "isTestName": "",
    "isMappingPath": "",
    "isMappingName": "",
    "isDataAccessPath": "",
    "isDataAccessName": "",
    "isDataStructurePath": "",
    "isDataStructureName": "",
    "isInterfaceStructuresPath": "",
    "isInterfaceStructuresName": "",
    "isEntryPointPath": "",
    "isEntryPointName": "",
    "treatFinalFieldsAsMandatory": false
  },
  "graphRestriction": {
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "removeByInheritance": "", // inheritance/annotation based filtering is done in a second step
    "removeByAnnotation": "",
    "removeByClassPackage": "", // cleanup the graph after inheritance/annotation based filtering is done
    "removeByClassName": "",
    "cutMappings": false,
    "cutEnum": true,
    "cutTests": true,
    "cutClient": true,
    "cutDataAccess": false,
    "cutInterfaceStructures": false,
    "cutDataStructures": false,
    "cutGetterAndSetter": true,
    "cutConstructors": true
  },
  "graphTraversal": {
    "forwardDepth": 6,
    "backwardDepth": 6,
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "hideMappings": false,
    "hideDataStructures": false,
    "hidePrivateMethods": true,
    "hideInterfaceCalls": true, // indirection: implementation -> interface (is hidden) -> implementation
    "onlyShowApplicationEntryPoints": false, // root node is included
    "useMethodCallsForStructureDiagram": "ForwardOnly" // ForwardOnly, BothDirections, No
  },
  "details": {
    "aggregation": "GroupByClass", // ByClass, GroupByClass, None
    "showClassGenericTypes": true,
    "showMethods": true,
    "showMethodParameterNames": true,
    "showMethodParameterTypes": true,
    "showMethodReturnType": true,
    "showPackageLevels": 2,
    "showDetailedClassStructure": true
  },
  "rootClass": "Plugin.Application.ConsoleCommands.EditReadingList.AddReadingListEntryManually",
  "extensionCallbackMethod": "" // qualified.class.name#methodName - signature: public static String method(String)
}
diagram meta data end '/



digraph g {
    rankdir="TB"
    splines=polyline
    

'nodes 
subgraph cluster_1072845520 { 
   	label=Application
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   DIContainer160408811[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)DIContainer</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   path: File [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   readingArchive: ReadingArchive [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   readingList: ReadingList [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ GetReadingArchive(): ReadingArchive</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

StateDictionary160408811[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)StateDictionary</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   dic: Map&lt;State, ConsoleCommand[]&gt; [0..*]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ GetOptions(appState: State): ConsoleCommand[]</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

subgraph cluster_1770848053 { 
   	label=Model
	labeljust=l
	fillcolor="#d8d8d8"
	style=filled
   
   Book481104144[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Book</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   Author: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   Genre: EnumSet&lt;Genre&gt; [0..*]</TD></TR>
<TR><TD ALIGN="LEFT" >-   Pagecount: int [1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   Title: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   language: Language [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ Author(): String</TD></TR>
<TR><TD ALIGN="LEFT" >+ Genre(): EnumSet&lt;Genre&gt;</TD></TR>
<TR><TD ALIGN="LEFT" >+ Pagecount(): int</TD></TR>
<TR><TD ALIGN="LEFT" >+ Title(): String</TD></TR>
<TR><TD ALIGN="LEFT" >+ language(): Language</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

ReadingArchive481104144[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)ReadingArchive</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   archive: ArrayList&lt;ReadingArchiveEntry&gt; [0..*]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ AddEntry(entry: ReadingArchiveEntry)</TD></TR>
<TR><TD ALIGN="LEFT" >+ RemoveEntry(b: Book): boolean</TD></TR>
<TR><TD ALIGN="LEFT" >+ searchByAuthor(author: String): List&lt;ReadingArchiveEntry&gt;</TD></TR>
<TR><TD ALIGN="LEFT" >+ searchByTitle(title: String): List&lt;ReadingArchiveEntry&gt;</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

ReadingArchiveEntry481104144[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)ReadingArchiveEntry</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   book: Book [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   comment: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   finishedReading: BookDateWrapper [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   startedReading: BookDateWrapper [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ book(): Book</TD></TR>
<TR><TD ALIGN="LEFT" >+ comment(): String</TD></TR>
<TR><TD ALIGN="LEFT" >+ finishedReading(): BookDateWrapper</TD></TR>
<TR><TD ALIGN="LEFT" >+ startedReading(): BookDateWrapper</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

ReadingList481104144[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)ReadingList</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >#   readingList: ArrayList&lt;ReadingListEntry&gt; [0..*]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ addReadingListEntry(entry: ReadingListEntry)</TD></TR>
<TR><TD ALIGN="LEFT" >+ removeEntry(entryToRemove: ReadingListEntry)</TD></TR>
<TR><TD ALIGN="LEFT" >+ searchByAuthor(author: String): List&lt;ReadingListEntry&gt;</TD></TR>
<TR><TD ALIGN="LEFT" >+ searchByTitle(title: String): List&lt;ReadingListEntry&gt;</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

ReadingListEntry481104144[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)ReadingListEntry</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   book: Book [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   comment: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   owned: boolean [1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ acquireBook()</TD></TR>
<TR><TD ALIGN="LEFT" >+ book(): Book</TD></TR>
<TR><TD ALIGN="LEFT" >+ owned(): boolean</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];
} 

subgraph cluster_622202847 { 
   	label=ConsoleCommands
	labeljust=l
	fillcolor="#d8d8d8"
	style=filled
   
   AcquireBook1398555944[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)AcquireBook</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >#   container: DIContainer [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ description(): String</TD></TR>
<TR><TD ALIGN="LEFT" >+ execute(): State</TD></TR>
<TR><TD ALIGN="LEFT" >+ name(): String</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

AddReadingArchiveEntryManually167638088[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)AddReadingArchiveEntryManually</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >#   container: DIContainer [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ description(): String</TD></TR>
<TR><TD ALIGN="LEFT" >+ execute(): State</TD></TR>
<TR><TD ALIGN="LEFT" >+ name(): String</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

AddReadingListEntryByWebSearch1398555944[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)AddReadingListEntryByWebSearch</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   container: DIContainer [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ description(): String</TD></TR>
<TR><TD ALIGN="LEFT" >+ execute(): State</TD></TR>
<TR><TD ALIGN="LEFT" >+ name(): String</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

AddReadingListEntryManually1398555944[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)AddReadingListEntryManually</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   container: DIContainer [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ description(): String</TD></TR>
<TR><TD ALIGN="LEFT" >+ execute(): State</TD></TR>
<TR><TD ALIGN="LEFT" >+ name(): String</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

AddReadingListEntryToReadingArchive167638088[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)AddReadingListEntryToReadingArchive</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   container: DIContainer [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ description(): String</TD></TR>
<TR><TD ALIGN="LEFT" >+ execute(): State</TD></TR>
<TR><TD ALIGN="LEFT" >+ name(): String</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

AddReadingListEntryToReadingList1398555944[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)AddReadingListEntryToReadingList</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   container: DIContainer [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ description(): String</TD></TR>
<TR><TD ALIGN="LEFT" >+ execute(): State</TD></TR>
<TR><TD ALIGN="LEFT" >+ name(): String</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

AttachComment1398555944[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)AttachComment</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   container: DIContainer [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ description(): String</TD></TR>
<TR><TD ALIGN="LEFT" >+ execute(): State</TD></TR>
<TR><TD ALIGN="LEFT" >+ name(): String</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

Cancel4600838[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Cancel</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ description(): String</TD></TR>
<TR><TD ALIGN="LEFT" >+ execute(): State</TD></TR>
<TR><TD ALIGN="LEFT" >+ name(): String</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

EditReadingArchive986665920[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)EditReadingArchive</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   container: DIContainer [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ description(): String</TD></TR>
<TR><TD ALIGN="LEFT" >+ execute(): State</TD></TR>
<TR><TD ALIGN="LEFT" >+ name(): String</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

EditReadingList986665920[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)EditReadingList</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   container: DIContainer [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ description(): String</TD></TR>
<TR><TD ALIGN="LEFT" >+ execute(): State</TD></TR>
<TR><TD ALIGN="LEFT" >+ name(): String</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

Exit4600838[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Exit</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >#   container: DIContainer [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ description(): String</TD></TR>
<TR><TD ALIGN="LEFT" >+ execute(): State</TD></TR>
<TR><TD ALIGN="LEFT" >+ name(): String</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

LoadLibrary73560600[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)LoadLibrary</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   container: DIContainer [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >- FindSeparatorIndex(listOfStrings: ArrayList&lt;String&gt;): int</TD></TR>
<TR><TD ALIGN="LEFT" >- ParseStringToArchiveEntries(subList: List&lt;String&gt;): ArrayList&lt;ReadingArchiveEntry&gt;</TD></TR>
<TR><TD ALIGN="LEFT" >- ParseStringToListEntries(subList: List&lt;String&gt;): ArrayList&lt;ReadingListEntry&gt;</TD></TR>
<TR><TD ALIGN="LEFT" >+ description(): String</TD></TR>
<TR><TD ALIGN="LEFT" >+ execute(): State</TD></TR>
<TR><TD ALIGN="LEFT" >+ name(): String</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

NewLibrary73560600[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)NewLibrary</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   container: DIContainer [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ description(): String</TD></TR>
<TR><TD ALIGN="LEFT" >+ execute(): State</TD></TR>
<TR><TD ALIGN="LEFT" >+ name(): String</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

RemoveBookFromReadingList1398555944[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)RemoveBookFromReadingList</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   container: DIContainer [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ description(): String</TD></TR>
<TR><TD ALIGN="LEFT" >+ execute(): State</TD></TR>
<TR><TD ALIGN="LEFT" >+ name(): String</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

ShowOwnedBooks868104187[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)ShowOwnedBooks</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   container: DIContainer [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ description(): String</TD></TR>
<TR><TD ALIGN="LEFT" >+ execute(): State</TD></TR>
<TR><TD ALIGN="LEFT" >+ name(): String</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

ShowReadingArchive986665920[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)ShowReadingArchive</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   container: DIContainer [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ description(): String</TD></TR>
<TR><TD ALIGN="LEFT" >+ execute(): State</TD></TR>
<TR><TD ALIGN="LEFT" >+ name(): String</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

ShowReadingArchiveByAuthor1671248891[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)ShowReadingArchiveByAuthor</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >#   container: DIContainer [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ description(): String</TD></TR>
<TR><TD ALIGN="LEFT" >+ execute(): State</TD></TR>
<TR><TD ALIGN="LEFT" >+ name(): String</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

ShowReadingArchiveByTitle1671248891[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)ShowReadingArchiveByTitle</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >#   container: DIContainer [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ description(): String</TD></TR>
<TR><TD ALIGN="LEFT" >+ execute(): State</TD></TR>
<TR><TD ALIGN="LEFT" >+ name(): String</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

ShowReadingList986665920[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)ShowReadingList</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >#   container: DIContainer [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ description(): String</TD></TR>
<TR><TD ALIGN="LEFT" >+ execute(): State</TD></TR>
<TR><TD ALIGN="LEFT" >+ name(): String</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

ShowReadingListByAuthor868104187[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)ShowReadingListByAuthor</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   container: DIContainer [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ description(): String</TD></TR>
<TR><TD ALIGN="LEFT" >+ execute(): State</TD></TR>
<TR><TD ALIGN="LEFT" >+ name(): String</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

ShowReadingListByTitle868104187[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)ShowReadingListByTitle</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   container: DIContainer [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ description(): String</TD></TR>
<TR><TD ALIGN="LEFT" >+ execute(): State</TD></TR>
<TR><TD ALIGN="LEFT" >+ name(): String</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

ShowStatistics986665920[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)ShowStatistics</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   container: DIContainer [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ description(): String</TD></TR>
<TR><TD ALIGN="LEFT" >+ execute(): State</TD></TR>
<TR><TD ALIGN="LEFT" >+ name(): String</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

ShowUnownedBooks868104187[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)ShowUnownedBooks</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   container: DIContainer [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ description(): String</TD></TR>
<TR><TD ALIGN="LEFT" >+ execute(): State</TD></TR>
<TR><TD ALIGN="LEFT" >- formatWishListOutput(content: List&lt;ReadingListEntry&gt;): String</TD></TR>
<TR><TD ALIGN="LEFT" >+ name(): String</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];
} 
} 

subgraph cluster_1901307053 { 
   	label=Plugin
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   GoogleBooksWebApi1901307053[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)GoogleBooksWebApi</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ searchForBookByTitle(bookTitle: String): ArrayList&lt;Book&gt;</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

JsonParser1901307053[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)JsonParser</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >- extractResponses(response: String): String[]</TD></TR>
<TR><TD ALIGN="LEFT" >+ parseHttpResponseToBooks(response: String): ArrayList&lt;Book&gt;</TD></TR>
<TR><TD ALIGN="LEFT" >- parseIntoBook(item: String): Book</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];
} 

subgraph cluster_2342 { 
   	label=IO
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   Input190330273[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Input</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ GetOption(numberOfValidOptions: int): int</TD></TR>
<TR><TD ALIGN="LEFT" >+ LoadTextFile(file: File): ArrayList&lt;String&gt;</TD></TR>
<TR><TD ALIGN="LEFT" >+ parseFilePath(path: String): File</TD></TR>
<TR><TD ALIGN="LEFT" >+ promptMsg(msg: String): String</TD></TR>
<TR><TD ALIGN="LEFT" >+ promptUserForDate(): BookDateWrapper</TD></TR>
<TR><TD ALIGN="LEFT" >+ promptUserForGenres(): EnumSet&lt;Genre&gt;</TD></TR>
<TR><TD ALIGN="LEFT" >+ promptUserForListChoice(list: List&lt;T&gt;): T</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

Output190330273[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Output</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ parseGenreOptions(options: String[]): String</TD></TR>
<TR><TD ALIGN="LEFT" >+ parseStateHelp(options: ConsoleCommand[]): String</TD></TR>
<TR><TD ALIGN="LEFT" >+ parseStateOptions(options: ConsoleCommand[]): String</TD></TR>
<TR><TD ALIGN="LEFT" >- printHeaderLine()</TD></TR>
<TR><TD ALIGN="LEFT" >+ saveToTextFile(content: String, path: File)</TD></TR>
<TR><TD ALIGN="LEFT" >+ showHeaderReadingArchive()</TD></TR>
<TR><TD ALIGN="LEFT" >+ showHeaderReadingList()</TD></TR>
<TR><TD ALIGN="LEFT" >+ showOutput(message: String)</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];
} 

'edges    
AcquireBook1398555944 -> DIContainer160408811[label="container
[0..1]"];
AcquireBook1398555944 -> ReadingList481104144[label="execute() -> searchByTitle()"];
AddReadingArchiveEntryManually167638088 -> DIContainer160408811[label="container
[0..1]"];
AddReadingListEntryByWebSearch1398555944 -> DIContainer160408811[label="container
[0..1]"];
AddReadingListEntryByWebSearch1398555944 -> GoogleBooksWebApi1901307053[arrowhead=none];
AddReadingListEntryByWebSearch1398555944 -> Output190330273[label="execute() -> showOutput()"];
AddReadingListEntryByWebSearch1398555944 -> ReadingList481104144[label="execute() -> addReadingListEntry()"];
AddReadingListEntryManually1398555944 -> AcquireBook1398555944[arrowhead=none];
AddReadingListEntryManually1398555944 -> AddReadingArchiveEntryManually167638088[arrowhead=none];
AddReadingListEntryManually1398555944 -> AddReadingListEntryByWebSearch1398555944[arrowhead=none];
AddReadingListEntryManually1398555944 -> AddReadingListEntryToReadingArchive167638088[arrowhead=none];
AddReadingListEntryManually1398555944 -> AddReadingListEntryToReadingList1398555944[arrowhead=none];
AddReadingListEntryManually1398555944 -> AttachComment1398555944[arrowhead=none];
AddReadingListEntryManually1398555944 -> Cancel4600838[arrowhead=none];
AddReadingListEntryManually1398555944 -> DIContainer160408811[label="container
[0..1]"];
AddReadingListEntryManually1398555944 -> EditReadingArchive986665920[arrowhead=none];
AddReadingListEntryManually1398555944 -> EditReadingList986665920[arrowhead=none];
AddReadingListEntryManually1398555944 -> Exit4600838[arrowhead=none];
AddReadingListEntryManually1398555944 -> LoadLibrary73560600[arrowhead=none];
AddReadingListEntryManually1398555944 -> NewLibrary73560600[arrowhead=none];
AddReadingListEntryManually1398555944 -> Output190330273[label="execute() -> showOutput()"];
AddReadingListEntryManually1398555944 -> ReadingList481104144[label="execute() -> addReadingListEntry()"];
AddReadingListEntryManually1398555944 -> RemoveBookFromReadingList1398555944[arrowhead=none];
AddReadingListEntryManually1398555944 -> ShowOwnedBooks868104187[arrowhead=none];
AddReadingListEntryManually1398555944 -> ShowReadingArchive986665920[arrowhead=none];
AddReadingListEntryManually1398555944 -> ShowReadingArchiveByAuthor1671248891[arrowhead=none];
AddReadingListEntryManually1398555944 -> ShowReadingArchiveByTitle1671248891[arrowhead=none];
AddReadingListEntryManually1398555944 -> ShowReadingList986665920[arrowhead=none];
AddReadingListEntryManually1398555944 -> ShowReadingListByAuthor868104187[arrowhead=none];
AddReadingListEntryManually1398555944 -> ShowReadingListByTitle868104187[arrowhead=none];
AddReadingListEntryManually1398555944 -> ShowStatistics986665920[arrowhead=none];
AddReadingListEntryManually1398555944 -> ShowUnownedBooks868104187[arrowhead=none];
AddReadingListEntryToReadingArchive167638088 -> DIContainer160408811[label="container
[0..1]"];
AddReadingListEntryToReadingArchive167638088 -> Output190330273[label="execute() -> showOutput()"];
AddReadingListEntryToReadingArchive167638088 -> ReadingArchive481104144[label="execute() -> AddEntry()"];
AddReadingListEntryToReadingArchive167638088 -> ReadingListEntry481104144[label="execute() -> book()"];
AddReadingListEntryToReadingList1398555944 -> DIContainer160408811[label="container
[0..1]"];
AttachComment1398555944 -> DIContainer160408811[label="container
[0..1]"];
AttachComment1398555944 -> ReadingList481104144[label="execute() -> searchByTitle()"];
DIContainer160408811 -> ReadingArchive481104144[label="readingArchive
[0..1]"];
DIContainer160408811 -> ReadingList481104144[label="readingList
[0..1]"];
EditReadingArchive986665920 -> DIContainer160408811[label="container
[0..1]"];
EditReadingList986665920 -> DIContainer160408811[label="container
[0..1]"];
Exit4600838 -> DIContainer160408811[label="container
[0..1]"];
Exit4600838 -> Input190330273[label="execute() -> promptMsg()"];
Exit4600838 -> Output190330273[label="execute() -> saveToTextFile()"];
GoogleBooksWebApi1901307053 -> JsonParser1901307053[label="searchForBookByTitle() -> parseHttpResponseToBooks()"];
LoadLibrary73560600 -> DIContainer160408811[label="container
[0..1]"];
NewLibrary73560600 -> DIContainer160408811[label="container
[0..1]"];
NewLibrary73560600 -> Input190330273[label="execute() -> promptMsg()"];
Output190330273 -> AcquireBook1398555944[arrowhead=none];
Output190330273 -> AddReadingArchiveEntryManually167638088[arrowhead=none];
Output190330273 -> AddReadingListEntryByWebSearch1398555944[arrowhead=none];
Output190330273 -> AddReadingListEntryManually1398555944[arrowhead=none];
Output190330273 -> AddReadingListEntryToReadingArchive167638088[arrowhead=none];
Output190330273 -> AddReadingListEntryToReadingList1398555944[arrowhead=none];
Output190330273 -> AttachComment1398555944[arrowhead=none];
Output190330273 -> Cancel4600838[arrowhead=none];
Output190330273 -> EditReadingArchive986665920[arrowhead=none];
Output190330273 -> EditReadingList986665920[arrowhead=none];
Output190330273 -> Exit4600838[arrowhead=none];
Output190330273 -> LoadLibrary73560600[arrowhead=none];
Output190330273 -> NewLibrary73560600[arrowhead=none];
Output190330273 -> RemoveBookFromReadingList1398555944[arrowhead=none];
Output190330273 -> ShowOwnedBooks868104187[arrowhead=none];
Output190330273 -> ShowReadingArchive986665920[arrowhead=none];
Output190330273 -> ShowReadingArchiveByAuthor1671248891[arrowhead=none];
Output190330273 -> ShowReadingArchiveByTitle1671248891[arrowhead=none];
Output190330273 -> ShowReadingList986665920[arrowhead=none];
Output190330273 -> ShowReadingListByAuthor868104187[arrowhead=none];
Output190330273 -> ShowReadingListByTitle868104187[arrowhead=none];
Output190330273 -> ShowStatistics986665920[arrowhead=none];
Output190330273 -> ShowUnownedBooks868104187[arrowhead=none];
ReadingArchive481104144 -> ReadingArchiveEntry481104144[label="archive
[0..*]"];
ReadingList481104144 -> ReadingListEntry481104144[label="readingList
[0..*]"];
RemoveBookFromReadingList1398555944 -> DIContainer160408811[label="container
[0..1]"];
ShowOwnedBooks868104187 -> DIContainer160408811[label="container
[0..1]"];
ShowReadingArchive986665920 -> DIContainer160408811[label="container
[0..1]"];
ShowReadingArchiveByAuthor1671248891 -> DIContainer160408811[label="container
[0..1]"];
ShowReadingArchiveByAuthor1671248891 -> Input190330273[label="execute() -> promptMsg()"];
ShowReadingArchiveByAuthor1671248891 -> ReadingArchive481104144[label="execute() -> searchByAuthor()"];
ShowReadingArchiveByTitle1671248891 -> DIContainer160408811[label="container
[0..1]"];
ShowReadingArchiveByTitle1671248891 -> Input190330273[label="execute() -> promptMsg()"];
ShowReadingArchiveByTitle1671248891 -> ReadingArchive481104144[label="execute() -> searchByTitle()"];
ShowReadingList986665920 -> DIContainer160408811[label="container
[0..1]"];
ShowReadingListByAuthor868104187 -> DIContainer160408811[label="container
[0..1]"];
ShowReadingListByAuthor868104187 -> Input190330273[label="execute() -> promptMsg()"];
ShowReadingListByAuthor868104187 -> ReadingList481104144[label="execute() -> searchByAuthor()"];
ShowReadingListByTitle868104187 -> DIContainer160408811[label="container
[0..1]"];
ShowReadingListByTitle868104187 -> Input190330273[label="execute() -> promptMsg()"];
ShowReadingListByTitle868104187 -> ReadingList481104144[label="execute() -> searchByTitle()"];
ShowStatistics986665920 -> DIContainer160408811[label="container
[0..1]"];
ShowUnownedBooks868104187 -> DIContainer160408811[label="container
[0..1]"];
StateDictionary160408811 -> AddReadingListEntryManually1398555944[label="dic
[0..*]", arrowhead=none];
    
}
@enduml