package Plugin.Application;

public enum State {
    INIT,
    MAIN,
    SHOWREADINGARCHIVE,
    EDITREADINGARCHIVE,
    SHOWREADINGLIST,

    EDITREADINGLIST,
    ADDBOOKTOREADINGLIST,
    STATISTIC,
    EXIT
}
